apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: vynnyal/productservice:latest
        resources:
          limits:
            memory: "56Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
