name: build-test
on:
  push:
    branches: [ main ]
    paths-ignore:
    - '**/*.gitattributes'
    - '**/*.gitignore'
    - '**/*.md'
  workflow_dispatch:
jobs:
  publish-image-aws-ecr:
    outputs:
      image-number: ${{steps.image-number-generator.outputs.image-number}}
    runs-on: ubuntu-latest
    steps:
      - name: Build Image Number
        id: image-number-generator
        run: echo image-number= ${{github.event.pull_request.number}} >> $GITHUB_OUTPUT

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-secret-access-key: ${{ secrets.GHA_KEY }}
          aws-access-key-id: ${{ secrets.GHA_ID }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: productservice
          IMAGE_TAG: productservice
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG